### ISSUE TITLE
Bug: Time Sync Problem in Filter Menu

### ISSUE THREAD

**Issue by risal-shefin** [Zeronfinity/CPfy#58]
### Steps to Reproduce

1. Untick Today of End Time
2. Set the upper range of End Time manually (using calendar)

### Expected Result

"X day(s) after" 's X should be synced automatically with the upper range of End Time.

### Actual Results

The actual result is the value of X remains the same. As a result, the contest list won't update correctly.

**Comment by Zeronfinity** [comment]
One thing to clarify.
When Today of End Time is unticked, "X day(s) after" should be hidden and not be used. Instead, the upper range of End Time set manually (using calendar) should be used only.

**Comment by risal-shefin** [comment]
Yeah, It's better.
