### ISSUE TITLE
Feature: Enable/Disable All Notifications

### ISSUE THREAD

**Issue by risal-shefin** [Zeronfinity/CPfy#60]
## Feature Suggestion

Feature: Enable/Disable All Notifications Together

### Description

A checkbox or button regarding enabling and disabling all OJ's contest notifications will be very helpful.

**Comment by Zeronfinity** [comment]
Do you mean something like this?

<img alt="Screenshot_1610819407" src="https://user-images.githubusercontent.com/34229687/104819103-94645580-5855-11eb-8081-5c3395dc6072.png" width=400>

Here, a *None* priority will disable the notification.
This has already been implemented in #55 and merged to master.

If the words "None" and "Priority" make this functionality hard to understand, you can suggest something on that though.

**Comment by risal-shefin** [comment]
No, I didn't mean that. I am actually suggesting an option, which will disable/enable the entire notification system at once. Traversing each and every contest to disable them is tedious work. 
I only need a few OJ's notifications. So I need to disable the rest. Disabling all of the notifications at first and then enable notification for some OJs will be easier for me.
