### ISSUE TITLE
Some contents of about page get cut/hidden on landscape mode

### ISSUE THREAD

**Issue by Rohijulislam** [Zeronfinity/CPfy#77]
## Bug Report

Bug: Contents get cut/hidden
App version: 1.1.0

### Description

Full contents of about page is not visible to user in landscape mode. A screenshot is attached for better understanding 

![Screenshot_20210125-210730_CPfy 1](https://user-images.githubusercontent.com/20037046/105725109-c1e68880-5f52-11eb-96ce-33b7d9173627.jpg)

### Steps to Reproduce

1. Launch the application
2.  Click more option of top bar
3. Click About to navigate about page
4. Rotate device in landscape mode 

### Expected Result
User should be able to see all the contents of about page in landscape mode.

**Comment by Zeronfinity** [comment]
Thanks for reporting. The screen has been turned into scrollable now to fix the issue. It will be rolled out in next update.

![Screenshot_1611593775](https://user-images.githubusercontent.com/34229687/105737781-8eaaf600-5f60-11eb-8e03-57b6980c6d4a.png)

![Screenshot_1611593777](https://user-images.githubusercontent.com/34229687/105737786-910d5000-5f60-11eb-85ac-9c8540a8a665.png)
